In [1]:
import os
import pandas as pd
import sqlite3
import matplotlib as plt

In [2]:
banco = sqlite3.connect('pesquisa_satisfacao.db')

### Criar a consulta SQL para trazer os dados que quero do banco

In [3]:
cur = banco.cursor()
sql = '''SELECT p.enunciado, r.resposta 
FROM perguntas p
INNER JOIN respostas r
    ON p.id = r.id_pergunta
'''
cur.execute(sql)
query = cur.fetchall()
#query é uma lista com todas as respostas

In [4]:
# query

### Criar nosso DataFrame

In [5]:
df = pd.read_sql(sql,banco)

In [13]:
df #O DataFrame com as perguntas e as respostas

                enunciado resposta
0     Gostou do produto?       sim
1     Gostou do produto?       sim
2     Gostou do produto?       nao
3     Gostou do produto?       sim
4     Gostou do produto?       nao
..                    ...      ...
145  Indicaria o produto?      sim
146  Indicaria o produto?      sim
147  Indicaria o produto?      nao
148  Indicaria o produto?      sim
149  Indicaria o produto?      sim

[150 rows x 2 columns]

In [6]:
def criar_lista(df,coluna):
    lista = []
    for dado in df[coluna]:
        lista.append(dado)
    return list(set(lista))

def criar_filtro(df,lista,coluna):
    dados = {}
    for dado in lista:
        mask = (df[coluna] == dado)
        dados[dado] = (df[mask])
    return dados

In [11]:
perguntas = criar_lista(df,'enunciado') #Salvar em uma lista todas as perguntas.

In [10]:
perguntas

['Gostou do produto? ', 'Indicaria o produto?', 'Compraria novamente? ']

In [16]:
dados_perguntas = criar_filtro(df,perguntas,'enunciado') #Criar o filtro de todas as perguntas.

In [17]:
dados_perguntas['Compraria novamente? ']

                enunciado resposta
50  Compraria novamente?       nao
51  Compraria novamente?       sim
52  Compraria novamente?       nao
53  Compraria novamente?       sim
54  Compraria novamente?       sim
55  Compraria novamente?       sim
56  Compraria novamente?       sim
57  Compraria novamente?       sim
58  Compraria novamente?       sim
59  Compraria novamente?       nao
60  Compraria novamente?       sim
61  Compraria novamente?       sim
62  Compraria novamente?       sim
63  Compraria novamente?       sim
64  Compraria novamente?       nao
65  Compraria novamente?       sim
66  Compraria novamente?       nao
67  Compraria novamente?       sim
68  Compraria novamente?       nao
69  Compraria novamente?       sim
70  Compraria novamente?       nao
71  Compraria novamente?       nao
72  Compraria novamente?       sim
73  Compraria novamente?       sim
74  Compraria novamente?       sim
75  Compraria novamente?       sim
76  Compraria novamente?       sim
77  Compraria novamente?       sim
78  Compraria novamente?       nao
79  Compraria novamente?       sim
80  Compraria novamente?       sim
81  Compraria novamente?       sim
82  Compraria novamente?       sim
83  Compraria novamente?       nao
84  Compraria novamente?       nao
85  Compraria novamente?       nao
86  Compraria novamente?       nao
87  Compraria novamente?       sim
88  Compraria novamente?       nao
89  Compraria novamente?       sim
90  Compraria novamente?       nao
91  Compraria novamente?       sim
92  Compraria novamente?       sim
93  Compraria novamente?       sim
94  Compraria novamente?       nao
95  Compraria novamente?       sim
96  Compraria novamente?       sim
97  Compraria novamente?       sim
98  Compraria novamente?       sim
99  Compraria novamente?       nao

In [ ]:
pergunta = df['enunciado'][0]

In [ ]:
df = df.rename(columns={'resposta':pergunta}, inplace = False)

In [ ]:
# df = df.drop(columns=['enunciado'])

In [ ]:
valores = df.value_counts()

In [ ]:
valores

In [ ]:
nao = valores[0]
sim = valores[1]

In [ ]:
df = pd.DataFrame({'resposta': [nao,sim],
                   'radius': [2439.7, 6051.8]},
                  index=['Não', 'Sim'])
plot = df.plot.pie(y='resposta', figsize=(5, 5))